from __future__ import annotations

from typing import Any, Dict, List

CATALOG_COLUMNS_V1_VERSION = "catalog_columns_v1"

CATALOG_COLUMNS_V1: List[Dict[str, Any]] = [
    {
        "id": "build_id",
        "label": "Build ID",
        "data_type": "string",
        "sortable": False,
        "filterable": True,
        "source": "builds.build_id",
        "index_priority": "high",
    },
    {
        "id": "created_at",
        "label": "Created",
        "data_type": "datetime",
        "sortable": True,
        "filterable": True,
        "source": "builds.created_at",
        "index_priority": "high",
    },
    {
        "id": "ruleset_id",
        "label": "Ruleset",
        "data_type": "string",
        "sortable": True,
        "filterable": True,
        "source": "builds.ruleset_id",
        "index_priority": "high",
    },
    {
        "id": "profile_id",
        "label": "Profile",
        "data_type": "string",
        "sortable": True,
        "filterable": True,
        "source": "builds.profile_id",
        "index_priority": "high",
    },
    {
        "id": "status",
        "label": "Status",
        "data_type": "string",
        "sortable": True,
        "filterable": True,
        "source": "builds.status",
        "index_priority": "high",
    },
    {
        "id": "class",
        "label": "Class",
        "data_type": "string",
        "sortable": True,
        "filterable": True,
        "source": "builds.class",
        "index_priority": "high",
    },
    {
        "id": "ascendancy",
        "label": "Ascendancy",
        "data_type": "string",
        "sortable": True,
        "filterable": True,
        "source": "builds.ascendancy",
        "index_priority": "high",
    },
    {
        "id": "main_skill",
        "label": "Main Skill",
        "data_type": "string",
        "sortable": False,
        "filterable": True,
        "source": "builds.main_skill",
        "index_priority": "high",
    },
    {
        "id": "full_dps",
        "label": "Full DPS",
        "data_type": "number",
        "sortable": True,
        "filterable": True,
        "source": "scenario_metrics.full_dps",
        "index_priority": "high",
    },
    {
        "id": "max_hit",
        "label": "Max Hit",
        "data_type": "number",
        "sortable": True,
        "filterable": True,
        "source": "scenario_metrics.max_hit",
        "index_priority": "high",
    },
    {
        "id": "armour",
        "label": "Armour",
        "data_type": "number",
        "sortable": False,
        "filterable": True,
        "source": "scenario_metrics.armour",
        "index_priority": "medium",
    },
    {
        "id": "evasion",
        "label": "Evasion",
        "data_type": "number",
        "sortable": False,
        "filterable": True,
        "source": "scenario_metrics.evasion",
        "index_priority": "medium",
    },
    {
        "id": "life",
        "label": "Life",
        "data_type": "number",
        "sortable": False,
        "filterable": True,
        "source": "scenario_metrics.life",
        "index_priority": "medium",
    },
    {
        "id": "mana",
        "label": "Mana",
        "data_type": "number",
        "sortable": False,
        "filterable": True,
        "source": "scenario_metrics.mana",
        "index_priority": "medium",
    },
    {
        "id": "utility_score",
        "label": "Utility",
        "data_type": "number",
        "sortable": False,
        "filterable": True,
        "source": "scenario_metrics.utility_score",
        "index_priority": "medium",
    },
    {
        "id": "total_cost_chaos",
        "label": "Total Cost",
        "data_type": "number",
        "sortable": True,
        "filterable": True,
        "source": "build_costs.total_cost_chaos",
        "index_priority": "high",
        "unit": "chaos",
    },
    {
        "id": "unknown_cost_count",
        "label": "Unknown Cost Count",
        "data_type": "integer",
        "sortable": False,
        "filterable": True,
        "source": "build_costs.unknown_cost_count",
        "index_priority": "medium",
    },
    {
        "id": "price_snapshot_id",
        "label": "Price Snapshot",
        "data_type": "string",
        "sortable": False,
        "filterable": True,
        "source": "build_costs.price_snapshot_id",
        "index_priority": "medium",
    },
    {
        "id": "dps_per_chaos",
        "label": "DPS per Chaos",
        "data_type": "number",
        "sortable": True,
        "filterable": False,
        "source": "derived",
        "index_priority": "medium",
    },
    {
        "id": "max_hit_per_chaos",
        "label": "Max Hit per Chaos",
        "data_type": "number",
        "sortable": True,
        "filterable": False,
        "source": "derived",
        "index_priority": "medium",
    },
]


def get_catalog_columns_v1() -> List[Dict[str, Any]]:
    return [dict(column) for column in CATALOG_COLUMNS_V1]
